---
- name: Add default route
  ansible.builtin.shell: ip route replace default via 192.168.56.1

- name: Set en_US as default locale
  ansible.builtin.command: update-locale LANG=en_US.UTF-8

- name: Installing APT dependencies
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - git
    - ruby-full
    - libpq-dev
    - zlib1g-dev
    - libsqlite3-dev
    - shared-mime-info
    - default-libmysqlclient-dev

- name: Installing GEM dependencies
  community.general.gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
  loop:
    - name: bundler
      version: 1.17.3
    - name: nokogiri
      version: 1.10.10
  loop_control:
    label: "{{ item.name }}"

- name: Cloning Railsgoat repository
  ansible.builtin.git:
    repo: https://github.com/OWASP/railsgoat
    dest: /myapp
    force: yes

- name: Modify Ruby version in Gemfile
  ansible.builtin.replace:
    path: /myapp/Gemfile
    regexp: '(^ruby ")(.*)"'
    replace: '\g<1>2.5.5"'

- name: Installing dependencies BUNDLE
  community.general.bundler:
    chdir: /myapp
    user_install: no

- name: Setup RailsGoat database
  ansible.builtin.command: /usr/local/bin/rails db:setup
  args:
    chdir: /myapp
    creates: /myapp/db/development.sqlite3

- name: Add RailsGoat systemd service unit
  copy:
    dest: /lib/systemd/system/railsgoat.service
    content: |
             [Unit]
             Description=RailsGoat
             After=sshd.service

             [Service]
             Type=simple
             WorkingDirectory=/myapp
             Environment=HOME=/myapp
             Environment=RAILS_ENV=development
             ExecStart=/usr/local/bin/puma -b tcp://0.0.0.0:80 --pidfile /myapp/tmp/pids/server.pid
             ExecStop=/bin/bash -c "kill -9 $(cat /myapp/tmp/pids/server.pid)"
             PIDFile=/myapp/tmp/pids/server.pid
             TimeoutSec=15
             Restart=always

             [Install]
             WantedBy=multi-user.target

- name: Create RailsGoat PID directory
  ansible.builtin.file:
    path: /myapp/tmp/pids
    state: directory

- name: Start and enable RailsGoat service at boot
  ansible.builtin.systemd:
    name: railsgoat
    state: started
    enabled: true
    daemon_reload: true
